import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import requests from "../utils/requests";
import Nav from "./../components/Nav";
import Results from "./../components/Results";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const req = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  console.log(req);

  return {
    props: {
      results: req.results,
    },
  };
};
